import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {deriveKey,seal,unseal,sealBytes,unsealBytes,to64,from64,allEvents,advanceDate} from '../public/vault.js';
import {convertLegacy} from '../public/migration.js';
const source=fs.readFileSync(new URL('../apps-script/Code.gs',import.meta.url),'utf8');
function backend(){let email='owner@gmail.com',googleEmail=email,googleSub='google-user',firebaseVerified=true,googleVerified=true,valid=true;const props={FIREBASE_API_KEY:'public-key',FAMILY_EMAILS:email};let writes=[];const context=vm.createContext({PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k],getProperties:()=>props,setProperty:(k,v)=>props[k]=v,deleteProperty:k=>delete props[k]})},UrlFetchApp:{fetch:(url,options)=>{const isFirebase=url.includes('accounts:lookup');if(isFirebase){const good=valid&&JSON.parse(options.payload).idToken==='valid-firebase';return {getResponseCode:()=>good?200:400,getContentText:()=>JSON.stringify({users:[{localId:'uid-owner',email,emailVerified:firebaseVerified,providerUserInfo:[{providerId:'google.com',rawId:'google-user'}]}]})};}assert.equal(options.headers.Authorization,'Bearer valid-google');return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({email:googleEmail,email_verified:googleVerified,sub:googleSub})};}},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({setMimeType:()=>JSON.parse(text)})},LockService:{getScriptLock:()=>({tryLock:()=>true,hasLock:()=>true,releaseLock(){}})},Date,JSON});vm.runInContext(source,context);return {context,props,writes,set:(k,v)=>{if(k==='email')email=v;if(k==='googleEmail')googleEmail=v;if(k==='googleSub')googleSub=v;if(k==='firebaseVerified')firebaseVerified=v;if(k==='googleVerified')googleVerified=v;if(k==='valid')valid=v;},auth:()=>context.authorize_({idToken:'valid-firebase',googleToken:'valid-google',userEmail:'someone-else@gmail.com',uid:'forged'})};}
test('Firebase and Google tokens must belong to the same allowed verified identity',()=>{const b=backend();assert.equal(b.auth().uid,'uid-owner');b.set('email','stranger@gmail.com');assert.throws(()=>b.auth(),/အသုံးပြုခွင့်/);b.set('email','owner@gmail.com');b.set('googleEmail','other@gmail.com');assert.throws(()=>b.auth(),/same person/);b.set('googleEmail','owner@gmail.com');b.set('googleSub','other-sub');assert.throws(()=>b.auth(),/same person/);b.set('googleSub','google-user');b.set('firebaseVerified',false);assert.throws(()=>b.auth());b.set('firebaseVerified',true);b.set('googleVerified',false);assert.throws(()=>b.auth());b.set('googleVerified',true);b.set('valid',false);assert.throws(()=>b.auth(),/invalid/);});
test('document ID guessing cannot access another user or folder',()=>{const b=backend(),ctx={uid:'uid-owner'},file={id:'drive-file',ownedByMe:true,parents:['folder-owner'],appProperties:{app:'family-vault-v2',uid:'uid-owner',role:'document'}};assert.equal(b.context.assertOwner_(file,ctx,'document','folder-owner').id,'drive-file');assert.throws(()=>b.context.assertOwner_(file,{uid:'uid-other'},'document','folder-owner'));assert.throws(()=>b.context.assertOwner_(file,ctx,'document','folder-other'));assert.throws(()=>b.context.assertOwner_({...file,ownedByMe:false},ctx,'document','folder-owner'));assert.throws(()=>b.context.assertOwner_(file,ctx,'database','folder-owner'));});
test('envelopes and reminders strip extra plaintext fields',()=>{const b=backend();const box={v:1,iv:'abcdefghijklmnop',ciphertext:'abcdefghijklmnopqrstuvwxyzABCDEF',password:'must-not-be-stored'};assert.equal(b.context.envelope_(box,1000).password,undefined);const reminders=b.context.reminders_([{kind:'due',date:'2026-10-01',accountNumber:'must-not-be-stored'}]);assert.equal(reminders[0].accountNumber,undefined);assert.throws(()=>b.context.reminders_([{kind:'unknown',date:'2026-10-01'}]));});
test('stale revision is rejected and save uses atomic Sheets batchUpdate chunks',()=>{const b=backend();let state={revision:3,salt:'salt'};b.context.read_=()=>state;let request;b.context.call_=(url,token,method,body)=>{request={url,body};return {};};const ctx={uid:'uid-owner',email:'owner@gmail.com',token:'valid-google'},storage={sheetId:'own-sheet',gridId:0};const box={v:1,iv:'abcdefghijklmnop',ciphertext:'abcdefghijklmnopqrstuvwxyzABCDEF'};assert.throws(()=>b.context.write_(ctx,storage,{revision:2,box,reminders:[]}),/Refresh/);const result=b.context.write_(ctx,storage,{revision:3,box,reminders:[],emailReminders:false});assert.equal(result.revision,4);assert.ok(request.url.includes('own-sheet:batchUpdate'));assert.equal(request.body.requests[0].updateCells.rows[0].values[0].userEnteredValue.stringValue,'4');assert.equal(request.body.requests.length,1);});
test('document authenticated encryption survives vault passphrase rotation',async()=>{const salt=to64(crypto.getRandomValues(new Uint8Array(32))),old=await deriveKey('first long private passphrase 123',salt),fresh=await deriveKey('second long private passphrase 456',salt);const raw=to64(crypto.getRandomValues(new Uint8Array(32)));const docKey=await crypto.subtle.importKey('raw',from64(raw),{name:'AES-GCM'},false,['encrypt','decrypt']);const bytes=new TextEncoder().encode('private passport bytes'),box=await sealBytes(bytes,docKey);const wrapped=await seal(raw,old),rewrapped=await seal(await unseal(wrapped,old),fresh);const recovered=await crypto.subtle.importKey('raw',from64(await unseal(rewrapped,fresh)),{name:'AES-GCM'},false,['decrypt']);assert.deepEqual(await unsealBytes(box,recovered),bytes);await assert.rejects(unseal(rewrapped,old));await assert.rejects(unseal(box,old));});
test('archived documents excluded and quarterly boundaries clamp correctly',()=>{const value={records:[],documents:[{id:'doc1',name:'Passport',status:'active',expiryDate:'2027-01-01'},{id:'doc2',status:'archived',expiryDate:'2020-01-01'}]};assert.equal(allEvents(value).length,1);assert.equal(advanceDate('2026-01-31','quarterly'),'2026-04-30');});
test('migration preserves linkage and warns for unavailable legacy encryption',()=>{const result=convertLegacy({accounts:[{id:'old-account',name:'Phone',encryptedPassword:'unknown-ciphertext'}],bills:[{id:'old-bill',billName:'Phone bill',nextDueDate:'2026-10-01',amount:10}],payments:[{billId:'old-bill',title:'Payment',amount:10,paymentDate:'2026-09-01'}]});assert.equal(result.records.length,2);assert.equal(result.payments[0].recordId,result.records[1].id);assert.ok(result.warnings.length>0);assert.equal(result.records[0].password,'');});
