/** Family Vault v2. Set Script Properties: FIREBASE_API_KEY, FAMILY_EMAILS.
 * Execute as owner; use each caller's validated Google OAuth token for ALL Drive/Sheets calls.
 * Never persist tokens or log request bodies. Client encrypts records/documents before sending.
 */
const DRIVE='https://www.googleapis.com/drive/v3/files';
const SHEETS='https://sheets.googleapis.com/v4/spreadsheets/';
function properties_(){return PropertiesService.getScriptProperties();}
function allowed_(){return (properties_().getProperty('FAMILY_EMAILS')||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);}
function response_(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);}
function doGet(){return response_({ok:false,error:'Authenticated POST required; public data endpoints disabled.'});}
function call_(url,token,method,body,contentType){const options={method:method||'get',headers:{Authorization:'Bearer '+token},muteHttpExceptions:true};if(body!==undefined){options.contentType=contentType||'application/json';options.payload=typeof body==='string'?body:JSON.stringify(body);}const r=UrlFetchApp.fetch(url,options),code=r.getResponseCode();if(code===401)throw Error('Google permission expired. Sign out and reconnect Google.');if(code<200||code>=300){if(code===403)throw Error('Google access denied. Enable Drive/Sheets APIs and grant Drive permission.');if(code===404)throw Error('Drive file missing or not accessible. Restore from a backup; do not reset your vault.');throw Error('Google API request failed ('+code+'). Retry or check API quota.');}const text=r.getContentText();return text?JSON.parse(text):{};}
function authorize_(req){const p=properties_(),apiKey=p.getProperty('FIREBASE_API_KEY');if(!apiKey||!allowed_().length)throw Error('Admin must set FIREBASE_API_KEY and FAMILY_EMAILS.');if(typeof req.idToken!=='string'||req.idToken.length>10000||typeof req.googleToken!=='string'||req.googleToken.length>10000)throw Error('Authentication required');const r=UrlFetchApp.fetch('https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='+encodeURIComponent(apiKey),{method:'post',contentType:'application/json',payload:JSON.stringify({idToken:req.idToken}),muteHttpExceptions:true});if(r.getResponseCode()!==200)throw Error('Firebase login expired or invalid');const u=(JSON.parse(r.getContentText()).users||[])[0];if(!u||u.disabled||!u.emailVerified||allowed_().indexOf((u.email||'').toLowerCase())<0)throw Error('ဤ Gmail ကို မိသားစုအသုံးပြုခွင့် မပေးထားပါ။');const google=call_('https://www.googleapis.com/oauth2/v3/userinfo',req.googleToken);const provider=(u.providerUserInfo||[]).find(x=>x.providerId==='google.com');if(!google.email_verified||google.email.toLowerCase()!==u.email.toLowerCase()||!provider||provider.rawId!==google.sub)throw Error('Firebase login and Google Drive account must be the same person.');if(!/^[A-Za-z0-9_-]{1,128}$/.test(u.localId))throw Error('Unsupported Firebase user ID');return {uid:u.localId,email:u.email.toLowerCase(),token:req.googleToken};}
function list_(ctx,q){return call_(DRIVE+'?q='+encodeURIComponent(q)+'&fields=files(id,name,mimeType,appProperties,ownedByMe,parents,trashed),nextPageToken&pageSize=100',ctx.token).files||[];}
function tag_(ctx,role){return {app:'family-vault-v2',uid:ctx.uid,role:role};}
function assertOwner_(file,ctx,role,parent){if(!file||!file.ownedByMe||file.trashed||!file.appProperties||file.appProperties.uid!==ctx.uid||file.appProperties.app!=='family-vault-v2'||file.appProperties.role!==role||(parent&&!(file.parents||[]).includes(parent)))throw Error('File does not belong to your private vault.');return file;}
function lookup_(ctx,id,role,parent){if(typeof id!=='string'||!/^[A-Za-z0-9_-]{5,200}$/.test(id))throw Error('Invalid file ID');return assertOwner_(call_(DRIVE+'/'+encodeURIComponent(id)+'?fields=id,mimeType,ownedByMe,parents,appProperties,trashed',ctx.token),ctx,role,parent);}
function findOne_(ctx,q,role,parent){const files=list_(ctx,q);if(files.length>1)throw Error('Multiple vault folders/databases found. Ask the owner to remove duplicates after taking backups.');return files.length?assertOwner_(files[0],ctx,role,parent):null;}
function provision_(ctx){const marker="trashed=false and appProperties has { key='app' and value='family-vault-v2' } and appProperties has { key='uid' and value='"+ctx.uid+"' }";let folder=findOne_(ctx,marker+" and appProperties has { key='role' and value='folder' }",'folder');if(!folder)folder=call_(DRIVE+'?fields=id',ctx.token,'post',{name:'Family Vault — Private',mimeType:'application/vnd.google-apps.folder',appProperties:tag_(ctx,'folder')});let db=findOne_(ctx,marker+" and '"+folder.id+"' in parents and appProperties has { key='role' and value='database' }",'database',folder.id);if(!db)db=call_(DRIVE+'?fields=id',ctx.token,'post',{name:'Family Vault — Encrypted Database',mimeType:'application/vnd.google-apps.spreadsheet',parents:[folder.id],appProperties:tag_(ctx,'database')});const metadata=call_(SHEETS+db.id+'?fields=sheets.properties',ctx.token);const sheet=metadata.sheets.find(s=>s.properties.title==='Vault')||metadata.sheets[0];if(!sheet)throw Error('Database sheet missing');if(sheet.properties.title!=='Vault')call_(SHEETS+db.id+':batchUpdate',ctx.token,'post',{requests:[{updateSheetProperties:{properties:{sheetId:sheet.properties.sheetId,title:'Vault'},fields:'title'}}]});const state=call_(SHEETS+db.id+'/values/Vault!A1:D202',ctx.token).values||[];if(!state.length){const salt=Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,Utilities.getUuid()+Utilities.getUuid()));call_(SHEETS+db.id+'/values/Vault!A1:D2?valueInputOption=RAW',ctx.token,'put',{values:[['revision','salt','chunkCount','updatedAt'],['0',salt,'0',new Date().toISOString()]]});}return {folderId:folder.id,sheetId:db.id,gridId:sheet.properties.sheetId};}
function read_(ctx,storage){const rows=call_(SHEETS+storage.sheetId+'/values/Vault!A1:D202',ctx.token).values||[];if(rows.length<2||rows[0][0]!=='revision'||!rows[1][1])throw Error('Database metadata is damaged. Restore a backup.');const meta=rows[1],count=Number(meta[2]);if(!Number.isInteger(count)||count<0||count>100)throw Error('Invalid database chunk count');let box=null;if(count){const chunks=rows.slice(2,2+count);if(chunks.length!==count||chunks.some(r=>typeof r[0]!=='string'))throw Error('Database chunks missing');box=envelope_(JSON.parse(chunks.map(r=>r[0]).join('')),1000000);}return {ok:true,revision:Number(meta[0]),salt:meta[1],box:box,folderId:storage.folderId,sheetId:storage.sheetId};}
function envelope_(b,max){if(!b||b.v!==1||typeof b.iv!=='string'||!/^[A-Za-z0-9+/]{16}$/.test(b.iv)||typeof b.ciphertext!=='string'||!/^[A-Za-z0-9+/]+={0,2}$/.test(b.ciphertext)||b.ciphertext.length<24||b.ciphertext.length>max)throw Error('Invalid encrypted data or size limit exceeded');return {v:1,iv:b.iv,ciphertext:b.ciphertext};}
function reminders_(values){if(!Array.isArray(values)||values.length>1000)throw Error('Invalid reminders');return values.map(d=>{if(!d||!['due','renewal','expiry','document'].includes(d.kind)||!/^\d{4}-\d{2}-\d{2}$/.test(d.date))throw Error('Invalid reminder date');return {kind:d.kind,date:d.date};});}
function write_(ctx,storage,req){const state=read_(ctx,storage);if(req.revision!==state.revision)throw Error('အခြား device မှ ပြင်ထားပါသည်။ Refresh လုပ်ပြီး ပြန်ပြင်ပါ။');const b=envelope_(req.box,1000000),dates=reminders_(req.reminders),serialized=JSON.stringify(b),chunks=serialized.match(/.{1,30000}/g),revision=state.revision+1;const values=[[String(revision),state.salt,String(chunks.length),new Date().toISOString()]].concat(chunks.map(c=>[c]));call_(SHEETS+storage.sheetId+':batchUpdate',ctx.token,'post',{requests:[{updateCells:{range:{sheetId:storage.gridId,startRowIndex:1,endRowIndex:202,startColumnIndex:0,endColumnIndex:4},rows:values.map(row=>({values:row.map(v=>({userEnteredValue:{stringValue:v}}))})),fields:'userEnteredValue'}}]});let reminderConfigured=true;try{const leadDays=[1,2,7].includes(Number(req.reminderLeadDays))?Number(req.reminderLeadDays):2;if(req.emailReminders===true)properties_().setProperty('REM_'+ctx.uid,JSON.stringify({email:ctx.email,dates:dates,leadDays:leadDays}));else properties_().deleteProperty('REM_'+ctx.uid);}catch(_){reminderConfigured=false;}return {ok:true,revision:revision,reminderConfigured:reminderConfigured};}
function upload_(ctx,storage,req){const box=envelope_(req.box,4200000);const boundary='fv_'+Utilities.getUuid().replace(/-/g,'');const fileId=Utilities.getUuid(),metadata={name:fileId+'.fvdoc',mimeType:'application/json',parents:[storage.folderId],appProperties:tag_(ctx,'document')};const body='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(metadata)+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+JSON.stringify(box)+'\r\n--'+boundary+'--';const file=call_('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id',ctx.token,'post',body,'multipart/related; boundary='+boundary);return {ok:true,fileId:file.id};}
function doPost(e){let lock;try{if(!e||!e.postData||e.postData.contents.length>4500000)throw Error('Request exceeds size limit');const req=JSON.parse(e.postData.contents);if(!['load','save','uploadDocument','downloadDocument','trashDocument'].includes(req.action))throw Error('Unknown action');const ctx=authorize_(req);lock=LockService.getScriptLock();if(!lock.tryLock(10000))throw Error('Vault busy; retry shortly.');const storage=provision_(ctx);if(req.action==='load')return response_(read_(ctx,storage));if(req.action==='save')return response_(write_(ctx,storage,req));if(req.action==='uploadDocument')return response_(upload_(ctx,storage,req));lookup_(ctx,req.fileId,'document',storage.folderId);if(req.action==='downloadDocument')return response_({ok:true,box:envelope_(call_(DRIVE+'/'+encodeURIComponent(req.fileId)+'?alt=media',ctx.token),4200000)});call_(DRIVE+'/'+encodeURIComponent(req.fileId),ctx.token,'patch',{trashed:true});return response_({ok:true});}catch(error){return response_({ok:false,error:error.message||'Request failed'});}finally{if(lock&&lock.hasLock())lock.releaseLock();}}
// Per-user opt-in digests. Only metadata is stored here; never a Google access token.
function sendDailyReminders(){const p=properties_(),all=p.getProperties(),today=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd');Object.keys(all).filter(k=>k.startsWith('REM_')).forEach(k=>{const reminder=JSON.parse(all[k]),leadDays=[1,2,7].includes(Number(reminder.leadDays))?Number(reminder.leadDays):2,end=new Date();end.setDate(end.getDate()+leadDays);const endDate=Utilities.formatDate(end,Session.getScriptTimeZone(),'yyyy-MM-dd');if(!allowed_().includes(reminder.email)||all['SENT_'+k]===today)return;const overdue=reminder.dates.filter(d=>d.date<today).length,dueSoon=reminder.dates.filter(d=>d.date>=today&&d.date<=endDate).length;if(!overdue&&!dueSoon)return;MailApp.sendEmail(reminder.email,'Family Vault — private reminder','Your private vault has '+overdue+' overdue alert(s) and '+dueSoon+' alert(s) due today or within the next '+leadDays+' day(s). Open Family Vault to review them.');p.setProperty('SENT_'+k,today);});}
function installReminderTrigger(){ScriptApp.getProjectTriggers().filter(t=>t.getHandlerFunction()==='sendDailyReminders').forEach(t=>ScriptApp.deleteTrigger(t));ScriptApp.newTrigger('sendDailyReminders').timeBased().everyDays(1).atHour(8).create();}
